package neu.edu.entity;
// Generated 24 Apr, 2017 7:02:22 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProjectCategory generated by hbm2java
 */
public class ProjectCategory implements java.io.Serializable {

	private Integer categoryId;
	private UserAccount userAccount;
	private String categoryName;
	private String categoryDescription;
	private Set<UserProject> userProjects = new HashSet<UserProject>(0);

	public ProjectCategory() {
	}

	public ProjectCategory(String categoryName) {
		this.categoryName = categoryName;
	}

	public ProjectCategory(UserAccount userAccount, String categoryName, String categoryDescription,
			Set<UserProject> userProjects) {
		this.userAccount = userAccount;
		this.categoryName = categoryName;
		this.categoryDescription = categoryDescription;
		this.userProjects = userProjects;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	public Set<UserProject> getUserProjects() {
		return this.userProjects;
	}

	public void setUserProjects(Set<UserProject> userProjects) {
		this.userProjects = userProjects;
	}

}
