package neu.edu.entity;
// Generated 24 Apr, 2017 7:02:22 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserCreditCard generated by hbm2java
 */
public class UserCreditCard implements java.io.Serializable {

	private Integer cardId;
	private UserAccount userAccount;
	private int cardNumber;
	private int cvv;
	private String expiry;
	private Set<UserDonation> userDonations = new HashSet<UserDonation>(0);

	public UserCreditCard() {
	}

	public UserCreditCard(int cardNumber, int cvv, String expiry) {
		this.cardNumber = cardNumber;
		this.cvv = cvv;
		this.expiry = expiry;
	}

	public UserCreditCard(UserAccount userAccount, int cardNumber, int cvv, String expiry,
			Set<UserDonation> userDonations) {
		this.userAccount = userAccount;
		this.cardNumber = cardNumber;
		this.cvv = cvv;
		this.expiry = expiry;
		this.userDonations = userDonations;
	}

	public Integer getCardId() {
		return this.cardId;
	}

	public void setCardId(Integer cardId) {
		this.cardId = cardId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public int getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(int cardNumber) {
		this.cardNumber = cardNumber;
	}

	public int getCvv() {
		return this.cvv;
	}

	public void setCvv(int cvv) {
		this.cvv = cvv;
	}

	public String getExpiry() {
		return this.expiry;
	}

	public void setExpiry(String expiry) {
		this.expiry = expiry;
	}

	public Set<UserDonation> getUserDonations() {
		return this.userDonations;
	}

	public void setUserDonations(Set<UserDonation> userDonations) {
		this.userDonations = userDonations;
	}

}
