package neu.edu.entity;
// Generated 24 Apr, 2017 7:02:22 PM by Hibernate Tools 5.2.1.Final

/**
 * UserDonation generated by hbm2java
 */
public class UserDonation implements java.io.Serializable {

	private Integer donationId;
	private UserAccount userAccount;
	private UserCreditCard userCreditCard;
	private UserProject userProject;
	private int donationAmount;

	public UserDonation() {
	}

	public UserDonation(int donationAmount) {
		this.donationAmount = donationAmount;
	}

	public UserDonation(UserAccount userAccount, UserCreditCard userCreditCard, UserProject userProject,
			int donationAmount) {
		this.userAccount = userAccount;
		this.userCreditCard = userCreditCard;
		this.userProject = userProject;
		this.donationAmount = donationAmount;
	}

	public Integer getDonationId() {
		return this.donationId;
	}

	public void setDonationId(Integer donationId) {
		this.donationId = donationId;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public UserCreditCard getUserCreditCard() {
		return this.userCreditCard;
	}

	public void setUserCreditCard(UserCreditCard userCreditCard) {
		this.userCreditCard = userCreditCard;
	}

	public UserProject getUserProject() {
		return this.userProject;
	}

	public void setUserProject(UserProject userProject) {
		this.userProject = userProject;
	}

	public int getDonationAmount() {
		return this.donationAmount;
	}

	public void setDonationAmount(int donationAmount) {
		this.donationAmount = donationAmount;
	}

}
