package neu.edu.entity;
// Generated 24 Apr, 2017 7:02:22 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserProject generated by hbm2java
 */
public class UserProject implements java.io.Serializable {

	private Integer projectId;
	private ProjectCategory projectCategory;
	private UserAccount userAccount;
	private String projectName;
	private String projectDescription;
	private Date projectDeadline;
	private int amountRequired;
	private Integer amountReceived;
	private Set<UserComments> userCommentses = new HashSet<UserComments>(0);
	private Set<UserDonation> userDonations = new HashSet<UserDonation>(0);

	public UserProject() {
	}

	public UserProject(String projectName, int amountRequired) {
		this.projectName = projectName;
		this.amountRequired = amountRequired;
	}

	public UserProject(ProjectCategory projectCategory, UserAccount userAccount, String projectName,
			String projectDescription, Date projectDeadline, int amountRequired, Integer amountReceived,
			Set<UserComments> userCommentses, Set<UserDonation> userDonations) {
		this.projectCategory = projectCategory;
		this.userAccount = userAccount;
		this.projectName = projectName;
		this.projectDescription = projectDescription;
		this.projectDeadline = projectDeadline;
		this.amountRequired = amountRequired;
		this.amountReceived = amountReceived;
		this.userCommentses = userCommentses;
		this.userDonations = userDonations;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public ProjectCategory getProjectCategory() {
		return this.projectCategory;
	}

	public void setProjectCategory(ProjectCategory projectCategory) {
		this.projectCategory = projectCategory;
	}

	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectDescription() {
		return this.projectDescription;
	}

	public void setProjectDescription(String projectDescription) {
		this.projectDescription = projectDescription;
	}

	public Date getProjectDeadline() {
		return this.projectDeadline;
	}

	public void setProjectDeadline(Date projectDeadline) {
		this.projectDeadline = projectDeadline;
	}

	public int getAmountRequired() {
		return this.amountRequired;
	}

	public void setAmountRequired(int amountRequired) {
		this.amountRequired = amountRequired;
	}

	public Integer getAmountReceived() {
		return this.amountReceived;
	}

	public void setAmountReceived(Integer amountReceived) {
		this.amountReceived = amountReceived;
	}

	public Set<UserComments> getUserCommentses() {
		return this.userCommentses;
	}

	public void setUserCommentses(Set<UserComments> userCommentses) {
		this.userCommentses = userCommentses;
	}

	public Set<UserDonation> getUserDonations() {
		return this.userDonations;
	}

	public void setUserDonations(Set<UserDonation> userDonations) {
		this.userDonations = userDonations;
	}

}
